name: 'Build Keyball Firmware'

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout keymap repository'
        uses: actions/checkout@v4

      - name: 'Setup QMK Environment'
        # v3タグの解決に失敗するため、特定のコミットハッシュに固定します
        uses: qmk/qmk-setup@22333457047514336216a6983796bb36c39a8353

      - name: 'Compile firmware'
        run: qmk compile -kb keyball/keyball39 -km my_custom

      - name: 'Archive firmware'
        uses: actions/upload-artifact@v4
        with:
          name: keyball39_firmware
          path: keyball_keyball39_my_custom.uf2